# Generated by Django 4.1.3 on 2023-05-14 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='image',
            field=models.CharField(max_length=1024),
        ),
    ]
